#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flatpak
Version  : 1.12.7
Release  : 77
URL      : https://github.com/flatpak/flatpak/releases/download/1.12.7/flatpak-1.12.7.tar.xz
Source0  : https://github.com/flatpak/flatpak/releases/download/1.12.7/flatpak-1.12.7.tar.xz
Source1  : flatpak-init.service
Source2  : flatpak.tmpfiles
Summary  : Application sandboxing framework
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: flatpak-autostart = %{version}-%{release}
Requires: flatpak-bin = %{version}-%{release}
Requires: flatpak-config = %{version}-%{release}
Requires: flatpak-data = %{version}-%{release}
Requires: flatpak-lib = %{version}-%{release}
Requires: flatpak-libexec = %{version}-%{release}
Requires: flatpak-license = %{version}-%{release}
Requires: flatpak-locales = %{version}-%{release}
Requires: flatpak-services = %{version}-%{release}
Requires: glib-networking
Requires: gnupg
Requires: gsettings-desktop-schemas
Requires: xdg-desktop-portal-gtk
BuildRequires : bison
BuildRequires : buildreq-gnome
BuildRequires : dbus
BuildRequires : dbus-dev
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : gpgme
BuildRequires : gpgme-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libarchive-dev
BuildRequires : libassuan-dev
BuildRequires : libcap-dev
BuildRequires : libsoup-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(appstream-glib)
BuildRequires : pkgconfig(dconf)
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libarchive)
BuildRequires : pkgconfig(libgsystem)
BuildRequires : pkgconfig(libseccomp)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(libzstd)
BuildRequires : pkgconfig(ostree-1)
BuildRequires : pkgconfig(polkit-agent-1)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : pkgconfig(xau)
BuildRequires : pypi(pyparsing)
BuildRequires : sed
BuildRequires : valgrind
BuildRequires : xmlto
Patch1: 0002-add-cleanup-helpers.patch
Patch2: 0001-fix-xdg-override.patch

%description
<p align="center">
<img src="https://github.com/flatpak/flatpak/blob/master/flatpak.png?raw=true" alt="Flatpak icon"/>
</p>

%package autostart
Summary: autostart components for the flatpak package.
Group: Default

%description autostart
autostart components for the flatpak package.


%package bin
Summary: bin components for the flatpak package.
Group: Binaries
Requires: flatpak-data = %{version}-%{release}
Requires: flatpak-libexec = %{version}-%{release}
Requires: flatpak-config = %{version}-%{release}
Requires: flatpak-license = %{version}-%{release}
Requires: flatpak-services = %{version}-%{release}

%description bin
bin components for the flatpak package.


%package config
Summary: config components for the flatpak package.
Group: Default

%description config
config components for the flatpak package.


%package data
Summary: data components for the flatpak package.
Group: Data

%description data
data components for the flatpak package.


%package dev
Summary: dev components for the flatpak package.
Group: Development
Requires: flatpak-lib = %{version}-%{release}
Requires: flatpak-bin = %{version}-%{release}
Requires: flatpak-data = %{version}-%{release}
Provides: flatpak-devel = %{version}-%{release}
Requires: flatpak = %{version}-%{release}

%description dev
dev components for the flatpak package.


%package lib
Summary: lib components for the flatpak package.
Group: Libraries
Requires: flatpak-data = %{version}-%{release}
Requires: flatpak-libexec = %{version}-%{release}
Requires: flatpak-license = %{version}-%{release}

%description lib
lib components for the flatpak package.


%package libexec
Summary: libexec components for the flatpak package.
Group: Default
Requires: flatpak-config = %{version}-%{release}
Requires: flatpak-license = %{version}-%{release}

%description libexec
libexec components for the flatpak package.


%package license
Summary: license components for the flatpak package.
Group: Default

%description license
license components for the flatpak package.


%package locales
Summary: locales components for the flatpak package.
Group: Default

%description locales
locales components for the flatpak package.


%package services
Summary: services components for the flatpak package.
Group: Systemd services

%description services
services components for the flatpak package.


%prep
%setup -q -n flatpak-1.12.7
cd %{_builddir}/flatpak-1.12.7
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1659029898
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
%configure --disable-static --disable-documentation \
--with-profile-dir=/usr/share/defaults/etc/profile.d \
--disable-seccomp \
--enable-gdm-env-file
make

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :

%install
export SOURCE_DATE_EPOCH=1659029898
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/flatpak
cp %{_builddir}/flatpak-%{version}/COPYING %{buildroot}/usr/share/package-licenses/flatpak/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/flatpak-%{version}/subprojects/libglnx/COPYING %{buildroot}/usr/share/package-licenses/flatpak/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install
%find_lang flatpak
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/flatpak-init.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/tmpfiles.d/flatpak.conf
## install_append content
mkdir -p %{buildroot}/usr/share/dbus-1/system.d/
mv system-helper/org.freedesktop.Flatpak.SystemHelper.conf %{buildroot}/usr/share/dbus-1/system.d/

mkdir -p %{buildroot}/usr/lib/systemd/system/graphical.target.wants
ln -sf ../flatpak-init.service %{buildroot}/usr/lib/systemd/system/graphical.target.wants/flatpak-init.service

cp flatpak-cleanup.service %{buildroot}/usr/lib/systemd/system/flatpak-cleanup.service
mkdir -p %{buildroot}/usr/libexec
cp clr-flatpak-cleanup %{buildroot}/usr/libexec/clr-flatpak-cleanup

## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/systemd/system-environment-generators/60-flatpak-system-only
/usr/lib/systemd/user-environment-generators/60-flatpak

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/graphical.target.wants/flatpak-init.service

%files bin
%defattr(-,root,root,-)
/usr/bin/flatpak
/usr/bin/flatpak-bisect
/usr/bin/flatpak-coredumpctl

%files config
%defattr(-,root,root,-)
/usr/lib/sysusers.d/flatpak.conf
/usr/lib/tmpfiles.d/flatpak.conf

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Flatpak-1.0.typelib
/usr/share/bash-completion/completions/flatpak
/usr/share/dbus-1/interfaces/org.freedesktop.Flatpak.Authenticator.xml
/usr/share/dbus-1/interfaces/org.freedesktop.Flatpak.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Flatpak.xml
/usr/share/dbus-1/services/org.flatpak.Authenticator.Oci.service
/usr/share/dbus-1/services/org.freedesktop.Flatpak.service
/usr/share/dbus-1/services/org.freedesktop.portal.Flatpak.service
/usr/share/dbus-1/system-services/org.freedesktop.Flatpak.SystemHelper.service
/usr/share/dbus-1/system.d/org.freedesktop.Flatpak.SystemHelper.conf
/usr/share/defaults/etc/profile.d/flatpak.sh
/usr/share/fish/vendor_completions.d/flatpak.fish
/usr/share/flatpak/triggers/desktop-database.trigger
/usr/share/flatpak/triggers/gtk-icon-cache.trigger
/usr/share/flatpak/triggers/mime-database.trigger
/usr/share/gdm/env.d/flatpak.env
/usr/share/gir-1.0/*.gir
/usr/share/polkit-1/actions/org.freedesktop.Flatpak.policy
/usr/share/polkit-1/rules.d/org.freedesktop.Flatpak.rules
/usr/share/zsh/site-functions/_flatpak

%files dev
%defattr(-,root,root,-)
/usr/include/flatpak/flatpak-bundle-ref.h
/usr/include/flatpak/flatpak-enum-types.h
/usr/include/flatpak/flatpak-error.h
/usr/include/flatpak/flatpak-installation.h
/usr/include/flatpak/flatpak-installed-ref.h
/usr/include/flatpak/flatpak-instance.h
/usr/include/flatpak/flatpak-portal-error.h
/usr/include/flatpak/flatpak-ref.h
/usr/include/flatpak/flatpak-related-ref.h
/usr/include/flatpak/flatpak-remote-ref.h
/usr/include/flatpak/flatpak-remote.h
/usr/include/flatpak/flatpak-transaction.h
/usr/include/flatpak/flatpak-version-macros.h
/usr/include/flatpak/flatpak.h
/usr/lib64/libflatpak.so
/usr/lib64/pkgconfig/flatpak.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libflatpak.so.0
/usr/lib64/libflatpak.so.0.11207.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/clr-flatpak-cleanup
/usr/libexec/flatpak-bwrap
/usr/libexec/flatpak-dbus-proxy
/usr/libexec/flatpak-oci-authenticator
/usr/libexec/flatpak-portal
/usr/libexec/flatpak-session-helper
/usr/libexec/flatpak-system-helper
/usr/libexec/flatpak-validate-icon
/usr/libexec/revokefs-fuse

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/flatpak/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/graphical.target.wants/flatpak-init.service
/usr/lib/systemd/system/flatpak-cleanup.service
/usr/lib/systemd/system/flatpak-init.service
/usr/lib/systemd/system/flatpak-system-helper.service
/usr/lib/systemd/user/flatpak-oci-authenticator.service
/usr/lib/systemd/user/flatpak-portal.service
/usr/lib/systemd/user/flatpak-session-helper.service

%files locales -f flatpak.lang
%defattr(-,root,root,-)

